//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongGiuXe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_employee { get; set; }
        public string fullname { get; set; }
        public string identity_card_number { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
