//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongGiuXe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking_Package
    {
        public int ID_package { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int price { get; set; }
        public int duration { get; set; }
        public bool visible { get; set; }
    }
}
