//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongGiuXe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID_payment { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> paid_at { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int price { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
