//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongGiuXe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_Price
    {
        public int ID_unit_price { get; set; }
        public Nullable<int> day_in_week { get; set; }
        public Nullable<System.TimeSpan> start_time_in_day { get; set; }
        public Nullable<System.TimeSpan> end_time_in_day { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public int price { get; set; }
        public string description { get; set; }
    }
}
